// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4w5uYtfE_xNw55KNDPgKwv74LG8oM8RA',
    appId: '1:268000342375:web:27f266fefe6a9fc9243fc2',
    messagingSenderId: '268000342375',
    projectId: 'fitness-11248',
    authDomain: 'fitness-11248.firebaseapp.com',
    storageBucket: 'fitness-11248.appspot.com',
    measurementId: 'G-0YC1WECH1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB26b6yi2yKQ6BWMHi4RyIMvNPt7WbEqAA',
    appId: '1:268000342375:android:a356abfcc661926d243fc2',
    messagingSenderId: '268000342375',
    projectId: 'fitness-11248',
    storageBucket: 'fitness-11248.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG3KQW0H7wO-_k68klesZf0eYOiLeG48c',
    appId: '1:268000342375:ios:3365aa200cf27160243fc2',
    messagingSenderId: '268000342375',
    projectId: 'fitness-11248',
    storageBucket: 'fitness-11248.appspot.com',
    iosBundleId: 'com.example.cpFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG3KQW0H7wO-_k68klesZf0eYOiLeG48c',
    appId: '1:268000342375:ios:d6a21f22b2c2959e243fc2',
    messagingSenderId: '268000342375',
    projectId: 'fitness-11248',
    storageBucket: 'fitness-11248.appspot.com',
    iosBundleId: 'com.example.cpFitnessApp.RunnerTests',
  );
}
